<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<Title>User Activity Logger</Title>
		<Copyright>Asma El-Hadiedy</Copyright>
		<Company>Asma El-Hadiedy</Company>
		<Authors>Asma El-Hadiedy</Authors>
		<PackAsTool>False</PackAsTool>
		<IncludeSymbols>False</IncludeSymbols>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.TXT</PackageLicenseFile>
		
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Description>✅ "Lightweight with Rich Context"
✅ "Zero configuration for basic scenarios"
✅ "Built-in security with automatic redaction"
✅ "Perfect for admin panels and user management"
✅ "Under 5 minutes setup time"</Description>
		<Version>1.0.9</Version>
		<PackageTags>logging;audit;activity;aspnetcore;entityframework</PackageTags>
		<PackageProjectUrl>https://github.com/Asma-Elhadiedy/UserActivityLogger.git</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Asma-Elhadiedy/UserActivityLogger.git</RepositoryUrl>
		
	</PropertyGroup>
	
	<!-- .NET 9 gets EF Core 9 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.11" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>


</Project>
